service: sending-messages-codedeployment-bucket
provider:
  name: aws
  region: us-west-2
  stage: dev
resources:
  Resources:
    codeDeploymentBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: sending-messages-codedeployment-bucket-${self:provider.stage}
        # DeletionPolicy: Retain
  Outputs:
    CodeDeploymentBucketName:
      Value:
        Ref: codeDeploymentBucket
      Export:
        Name: "sending-messages-codedeployment-bucket-${self:provider.stage}-name"
