service: sending-messages-codedeployment-bucket
provider:
  name: aws
  region: us-west-2
  stage: dev
resources:
  Resources:
    codeDeploymentBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: sending-messages-codedeployment-bucket-${self:provider.stage}
        # DeletionPolicy: Retain
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - 'Content-Type'
              AllowedMethods:
                - GET
                - HEAD
              AllowedOrigins:
                - '*'
              ExposedHeaders:
                - Date
        PublicAccessBlockConfiguration:
          RestrictPublicBuckets: true
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
  Outputs:
    CodeDeploymentBucketName:
      Value:
        Ref: codeDeploymentBucket
      Export:
        Name: "sending-messages-codedeployment-bucket-${self:provider.stage}-name"
